### PR TITLE
Host Based Routing Lab: Include Certificate Generation Step

### PR DESCRIPTION
**Pull request by chuck-confluent**
See https://github.com/confluentinc/operator-earlyaccess/issues/51

Still actively drafting. Not ready for merge.

### CODE REVIEW

**Comment by chuck-confluent** [comment]
I will probably end up including https://github.com/confluentinc/operator-earlyaccess/issues/50 into this PR as well, since they are closely related

**Comment by chuck-confluent** [comment]
I would like to run through this end to end one more time myself before calling for reviewers.

**Comment by chuck-confluent** [comment]
Ok, this works beautifully now, end-to-end, in the lab portal! I did have to install the ingress controller and use an updated ingress definition as described in https://github.com/confluentinc/operator-earlyaccess/pull/54 . 

@yangpei1214 This PR is ready for your review and merge!

**Review by rohit2b — APPROVED** [review]
LGTM!

**Pull request merged**
