### PR TITLE
production-secure-deploy: Lab Enhancements

### PR DESCRIPTION
**Pull request by chuck-confluent**
Looking to address:

- https://github.com/confluentinc/operator-earlyaccess/issues/63
- https://github.com/confluentinc/operator-earlyaccess/issues/60
- https://github.com/confluentinc/operator-earlyaccess/issues/59

In short, the goal is to provide these enhancements:
- Use more secure LDAPS connection
- Use LdapAuthenticateCallbackHandler class instead of providing plaintext username and password
- Add groups to LDAP server to show off group search for RBAC
- Logically separate credentials into different secrets for clarity
- Include a set of pre-generated certs for people to use that will work out of the box for *.confluent.svc.cluster.local SANs

Not yet ready for review/merge

### CODE REVIEW

**Comment by chuck-confluent** [comment]
Tested in the confluent lab platform. Ready for review and merge

**Comment by chuck-confluent** [comment]
@rohit2b just pinging you on this. I'd love to get this merged so I can record a video for the course!

**Review by rohit2b — CHANGES_REQUESTED** [review]
Just one change to the CR YAML, otherwise everything looks great!

**Comment by chuck-confluent** [comment]
@rohit2b good call on the metrics reporter! Committed your suggestion. Feel free to merge

**Review by rohit2b — APPROVED** [review]
LGTM!

**Pull request merged**
